apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-redis-secret
  namespace: keda
spec:
  secretTargetRef:
    - key: REDIS_PASSWORD
      name: redis-password
      parameter: password
